<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Missing argument 1 for Modele_Oeuvres::obtenirBio(), called in C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php on line 114 and defined in C:\wamp64\www\ArtPublicMTL\modeles\Modele_oeuvres.php on line <i>199</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>240344</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0015</td><td bgcolor='#eeeeec' align='right'>247112</td><td bgcolor='#eeeeec'>Routeur::route(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>18</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0052</td><td bgcolor='#eeeeec' align='right'>347376</td><td bgcolor='#eeeeec'>Controleur_Public_AJAX->traite(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Routeur.php' bgcolor='#eeeeec'>...\Routeur.php<b>:</b>40</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0099</td><td bgcolor='#eeeeec' align='right'>438392</td><td bgcolor='#eeeeec'>Modele_Oeuvres->obtenirBio(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php' bgcolor='#eeeeec'>...\Controleur_Public_AJAX.php<b>:</b>114</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Missing argument 2 for Modele_Oeuvres::obtenirBio(), called in C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php on line 114 and defined in C:\wamp64\www\ArtPublicMTL\modeles\Modele_oeuvres.php on line <i>199</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>240344</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0015</td><td bgcolor='#eeeeec' align='right'>247112</td><td bgcolor='#eeeeec'>Routeur::route(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>18</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0052</td><td bgcolor='#eeeeec' align='right'>347376</td><td bgcolor='#eeeeec'>Controleur_Public_AJAX->traite(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Routeur.php' bgcolor='#eeeeec'>...\Routeur.php<b>:</b>40</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0099</td><td bgcolor='#eeeeec' align='right'>438392</td><td bgcolor='#eeeeec'>Modele_Oeuvres->obtenirBio(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php' bgcolor='#eeeeec'>...\Controleur_Public_AJAX.php<b>:</b>114</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Missing argument 3 for Modele_Oeuvres::obtenirBio(), called in C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php on line 114 and defined in C:\wamp64\www\ArtPublicMTL\modeles\Modele_oeuvres.php on line <i>199</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>240344</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0015</td><td bgcolor='#eeeeec' align='right'>247112</td><td bgcolor='#eeeeec'>Routeur::route(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>18</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0052</td><td bgcolor='#eeeeec' align='right'>347376</td><td bgcolor='#eeeeec'>Controleur_Public_AJAX->traite(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Routeur.php' bgcolor='#eeeeec'>...\Routeur.php<b>:</b>40</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0099</td><td bgcolor='#eeeeec' align='right'>438392</td><td bgcolor='#eeeeec'>Modele_Oeuvres->obtenirBio(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php' bgcolor='#eeeeec'>...\Controleur_Public_AJAX.php<b>:</b>114</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: nomCollectif in C:\wamp64\www\ArtPublicMTL\modeles\Modele_oeuvres.php on line <i>203</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>240344</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0015</td><td bgcolor='#eeeeec' align='right'>247112</td><td bgcolor='#eeeeec'>Routeur::route(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>18</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0052</td><td bgcolor='#eeeeec' align='right'>347376</td><td bgcolor='#eeeeec'>Controleur_Public_AJAX->traite(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Routeur.php' bgcolor='#eeeeec'>...\Routeur.php<b>:</b>40</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0099</td><td bgcolor='#eeeeec' align='right'>438392</td><td bgcolor='#eeeeec'>Modele_Oeuvres->obtenirBio(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php' bgcolor='#eeeeec'>...\Controleur_Public_AJAX.php<b>:</b>114</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: prenomArtiste in C:\wamp64\www\ArtPublicMTL\modeles\Modele_oeuvres.php on line <i>204</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>240344</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0015</td><td bgcolor='#eeeeec' align='right'>247112</td><td bgcolor='#eeeeec'>Routeur::route(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>18</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0052</td><td bgcolor='#eeeeec' align='right'>347376</td><td bgcolor='#eeeeec'>Controleur_Public_AJAX->traite(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Routeur.php' bgcolor='#eeeeec'>...\Routeur.php<b>:</b>40</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0099</td><td bgcolor='#eeeeec' align='right'>438392</td><td bgcolor='#eeeeec'>Modele_Oeuvres->obtenirBio(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php' bgcolor='#eeeeec'>...\Controleur_Public_AJAX.php<b>:</b>114</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined variable: nomArtiste in C:\wamp64\www\ArtPublicMTL\modeles\Modele_oeuvres.php on line <i>204</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0005</td><td bgcolor='#eeeeec' align='right'>240344</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0015</td><td bgcolor='#eeeeec' align='right'>247112</td><td bgcolor='#eeeeec'>Routeur::route(  )</td><td title='C:\wamp64\www\ArtPublicMTL\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>18</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0052</td><td bgcolor='#eeeeec' align='right'>347376</td><td bgcolor='#eeeeec'>Controleur_Public_AJAX->traite(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Routeur.php' bgcolor='#eeeeec'>...\Routeur.php<b>:</b>40</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0099</td><td bgcolor='#eeeeec' align='right'>438392</td><td bgcolor='#eeeeec'>Modele_Oeuvres->obtenirBio(  )</td><td title='C:\wamp64\www\ArtPublicMTL\controleurs\Controleur_Public_AJAX.php' bgcolor='#eeeeec'>...\Controleur_Public_AJAX.php<b>:</b>114</td></tr>
</table></font>
fjng